apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-labels
  labels:
    environment: production
    team: finance
    version: 1.2.3
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80