apiVersion: v1
kind: PersistentVolume
metadata:
  name:  nodejs-stateful-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity: 
    storage: 5Gi
  hostPath:
    path: /data/location
  
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodejs-stateful
  labels: 
    name:  nodejs-stateful
spec:
  # https://github.com/kubernetes/kubernetes/issues/69608
  serviceName: nodejs-stateful-service
  replicas: 3
  selector:
    matchLabels: 
      name: nodejs-stateful
  volumeClaimTemplates:
    - metadata:
        name:  nodejs-stateful-volume-claim
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      name: nodejs-stateful
      labels: 
        name:  nodejs-stateful
    spec:
      containers:
        - name: nodejs-stateful
          image: akhmadwildan/nodejs-stateful
          env: 
            - name: POD_NAME
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /app/data
              name:  nodejs-stateful-volume-claim

